### ISSUE TITLE
Тема проекта

### ISSUE THREAD

**Issue by Vlhub** [natalikatkowa/zlp_tech#2]
* Информационная система включает не только ПО. И далеко не любое ПО может использоваться в ИС. Компонентами ИС, как правило, являются СУБД, CMS..., но не блокнот, сапёр и пасьянс косынка. 
* Предлагаю внести небольшие коррекции в название темы: 

# «Проект информационной системы финансового планирования, предоставляющего услугу подбора индивидуальных инвестиционных предложений клиентам компании ZLP Tech».

**Comment by natalikatkowa** [comment]
Изменения внесены, спасибо за обратную связь!

**Comment by Vlhub** [comment]
До **Нового** года, надо обязательно выложить, согласовать и отредактировать ТЗ на проект!
